name: Lint

on: 
  push:
    branches: [ main ]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.12
          architecture: x64
  
      - name: Checkout PyTorch
        uses: actions/checkout@master

      - name: Install flake8
        run: |
          pip install flake8 flake8-html

      - name: Run flake8
        run: |   
          flake8 --format=html --htmldir=flake-report --exit-zero

      - name: Commit files
        run: |
          git config --local user.email "zp2188@columbia.edu"
          git config --local user.name "github-actions"
          git add .
          git commit -m "Add lint report" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
