# name: Flake8

# on: [push, pull_request]

# jobs:
#   flake8_py3:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup Python
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.7.12
#           architecture: x64
#       - name: Checkout PyTorch
#         uses: actions/checkout@master
#       - name: Install flake8
#         run: pip install flake8
#       - name: Run flake8
#         uses: suo/flake8-github-action@releases/v1
#         with:
#           checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
#           files: test-results/**/*.xm
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
name: Lint

on: [push, pull_request]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.12
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: |
          pip install flake8

      - name: Run flake8
        run: |   
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

