name: Postman

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12"]
    steps:
    - name: Install dependencies
      run: |
        npm install newman
          
    - name: running postman
      run: |
        node_modules/.bin/newman run https://api.getpostman.com/collections/18341107-79bbc61e-e7f6-4152-9324-4a5adeb4ca38?apikey=PMAK-61b2c1164bfcca0051634938-5c324410856a5ab2615f8de871a45bd6de --environment https://api.getpostman.com/environments/18341107-2824841b-f489-4c15-aff1-dadab7242eb2?apikey=PMAK-61b2c1164bfcca0051634938-5c324410856a5ab2615f8de871a45bd6de


