name: Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
          sudo apt-get update
          sudo apt-get install build-essential chrpath libssl-dev libxft-dev
          sudo apt-get install libfreetype6 libfreetype6-dev
          sudo apt-get install libfontconfig1 libfontconfig1-dev
          cd $RUNNER_TEMP
          export PHANTOM_JS="phantomjs-1.9.8-linux-x86_64"
          wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
          sudo tar xvjf $PHANTOM_JS.tar.bz2
          sudo mv $PHANTOM_JS /usr/local/share
          sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
          
    - name: analysis converage
      working-directory: ./unit_test
      run: |
        
        coverage run test_user_services.py
        coverage report --omit "test_*"
        coverage xml --omit "test_*" -o test-coverage.xml
        PERCENTAGE=$(coverage report --omit "test_*" | tail -c 5 | head -c -2 | xargs)
        echo "coverage = $PERCENTAGE%"
        echo "::set-output name=RATE::$PERCENTAGE"
        echo "::set-output name=COLOR::$([ $PERCENTAGE -lt 85 ] && echo important || echo success)"
        echo "::set-output name=HASH_SHORT::$(git rev-parse --short HEAD)"
        
    - name: Override Coverage Source Path for Sonar
      run: sed -i "s/\/home\/runner\/work\/LYPZ_4156_Project\/LYPZ_4156_Project\//\/unit_test\//g" test-coverage.xml
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

