name: Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
          sudo apt-get update
          sudo apt-get install build-essential chrpath libssl-dev libxft-dev -y
          sudo apt-get install libfreetype6 libfreetype6-dev -y
          sudo apt-get install libfontconfig1 libfontconfig1-dev -y
          cd $RUNNER_TEMP
          export PHANTOM_JS="phantomjs-2.1.1-linux-x86_64"
          wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
          sudo tar xvjf $PHANTOM_JS.tar.bz2
          sudo mv $PHANTOM_JS /usr/local/share
          sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin

    - name: analysis converage
      working-directory: ./unit_test
      run: |
        coverage run -m unittest discover
        coverage html
